version: "3.8"

services:
  foundry:
    container_name: foundry
    hostname: foundry_hostname
    init: true
    restart: "no"
    volumes:
      - type: bind
        source: ./data
        target: /data:Z
    environment:
      - FOUNDRY_PASSWORD=<your_password>
      - FOUNDRY_USERNAME=<your_username>
      - FOUNDRY_ADMIN_KEY=atropos
    # - CONTAINER_CACHE=/data/container_cache
    # - CONTAINER_PATCHES=/data/container_patches
    # - CONTAINER_PATCH_URLS=
    #   https://raw.githubusercontent.com/felddy/...
    #   https://raw.githubusercontent.com/felddy/...
    # - CONTAINER_PRESERVE_CONFIG=false
    # - CONTAINER_VERBOSE=true
    # - FOUNDRY_AWS_CONFIG=
    # - |
    #   FOUNDRY_DEMO_CONFIG={
    #   "worldName": "demo-world",
    #   "sourceZip": "/data/demo-world.zip",
    #   "resetSeconds": 3600
    #   }
    # - FOUNDRY_GID=foundry
    # - FOUNDRY_HOSTNAME=
    # - FOUNDRY_IP_DISCOVERY=
    # - FOUNDRY_LANGUAGE=
    # - FOUNDRY_LOCAL_HOSTNAME=
    # - FOUNDRY_LICENSE_KEY=
    # - FOUNDRY_MINIFY_STATIC_FILES=
    # - FOUNDRY_PASSWORD_SALT=
    # - FOUNDRY_PROXY_PORT=
    # - FOUNDRY_aPROXY_SSL=false
    # - FOUNDRY_RELEASE_URL=
    # - FOUNDRY_ROUTE_PREFIX=
    # - FOUNDRY_SSL_CERT=
    # - FOUNDRY_SSL_KEY=
    # - FOUNDRY_UID=foundry
    # - FOUNDRY_UPNP=false
    # - FOUNDRY_UPNP_LEASE_DURATION=
    # - FOUNDRY_VERSION=9.269
    # - FOUNDRY_WORLD=
    # - TIMEZONE=US/Eastern
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
        mode: host
      - target: 2222
        published: 2222
        protocol: tcp
        mode: host
